# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('dwebsummit_admin', '0002_auto_20180608_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('image', stdimage.models.StdImageField(upload_to=b'')),
            ],
            options={
                'verbose_name_plural': 'sponsors',
            },
        ),
    ]
