# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwebsummit_admin', '0003_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='type',
            field=models.CharField(choices=[('0', 'Regular Sponsor'), ('1', 'Lead Sponsor')], default='1', max_length=2),
        ),
    ]
