# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dwebsummit_admin', '0004_sponsor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='sponsorship_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
