# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwebsummit_admin', '0007_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfield',
            name='name',
            field=models.CharField(db_index=True, editable=False, max_length=100, unique=True),
        ),
    ]
