# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 05:02
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwebsummit_admin', '0008_auto_20180622_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='value',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
