# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 22:58
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('dwebsummit_admin', '0010_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(db_index=True, max_length=255, unique=True)),
                ('page_template', models.CharField(blank=True, default='text_page.html', help_text='Changes the html template.', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('banner_image', stdimage.models.StdImageField(upload_to=b'')),
                ('thumbnail_image', stdimage.models.StdImageField(upload_to=b'')),
                ('body_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('is_published', models.BooleanField(default=True)),
                ('next_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prev', to='dwebsummit_admin.Page')),
                ('people', models.ManyToManyField(to='dwebsummit_admin.Person')),
                ('prev_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next', to='dwebsummit_admin.Page')),
            ],
            options={
                'verbose_name_plural': 'pages',
            },
        ),
    ]
