# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dwebsummit_admin', '0012_auto_20180627_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('external_url', models.URLField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='NavbarLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('external_url', models.URLField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterField(
            model_name='page',
            name='page_url',
            field=models.CharField(blank=True, db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='people',
            field=models.ManyToManyField(blank=True, null=True, to='dwebsummit_admin.Person'),
        ),
        migrations.AddField(
            model_name='navbarlink',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dwebsummit_admin.Page'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dwebsummit_admin.Page'),
        ),
    ]
