# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwebsummit_admin', '0013_auto_20180628_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarlink',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
