# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwebsummit_admin', '0015_person_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='related_pages',
            field=models.ManyToManyField(blank=True, null=True, related_name='_page_related_pages_+', to='dwebsummit_admin.Page'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
