# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwebsummit_admin', '0016_auto_20180628_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='thumbnail_image',
        ),
        migrations.AlterField(
            model_name='page',
            name='people',
            field=models.ManyToManyField(blank=True, to='dwebsummit_admin.Person'),
        ),
        migrations.AlterField(
            model_name='page',
            name='related_pages',
            field=models.ManyToManyField(blank=True, related_name='_page_related_pages_+', to='dwebsummit_admin.Page'),
        ),
    ]
