# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-20 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwebsummit_admin', '0017_auto_20180628_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='person',
            name='featured_organizer_text',
            field=models.TextField(blank=True, default='', help_text='Short paragraph. Will be down next to iamge'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_featured_organizer',
            field=models.BooleanField(default=False, help_text='Will be highlighted on people page'),
        ),
    ]
